services:
  python-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/root
    image: python-dev
    shm_size: 4gb
    ports:
      - "8888:8888"
    platform: linux/amd64
    stdin_open: true
    tty: true
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]