[tool.poetry]
name = "python-deb"
version = "0.1.0"
description = ""
authors = ["sinhat98 <sinhat897205@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pyaudio = "^0.2.14"
librosa = "^0.10.2.post1"
onnxruntime = "^1.18.0"
mecab-python3 = "^1.0.9"
fastapi = "^0.111.0"
uvicorn = "^0.29.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
